### ISSUE TITLE
SQL Dev Web Login common .md requires updates

### ISSUE THREAD

**Issue by chrishoina** [oracle-livelabs/common#177]
Hi there,

The following .md document: https://oracle-livelabs.github.io/common/labs/sqldevweb-login/sqldevweb-login.md was first created in 2020, and last updated in 2022. Since this was a shared document, I wasn't sure how to suggest updates. But there have been some iterative changes to the application suite since this document was first created. 

As an example, it is still being referred to as "SQL Developer Web" instead of its current name "Database Actions." That is one small example, but there are others. Can somebody on the LL team assist with updating this shared document? 

Thanks!

Chris

**Comment by klazarz** [comment]
@anooshapilli Can you please work with Chris on this? Thanks

**Comment by stevenlemme** [comment]
Checked on 6/13/23 and Anoosha checked with Chris and said its in progress

**Comment by anooshapilli** [comment]
@chrishoina - Just checking in for an update on this issue.

**Comment by chrishoina** [comment]
I've just submitted a PR for this, reference: https://github.com/oracle-livelabs/common/pull/195

Thanks!
